WIP: 画面遷移図を作成
ws-4020/mobile-app-handson pull request #11
Opened 2021-01-25 07:29 UTC by tani-takanori

2021-01-26 11:07 UTC, in-a-paddy requested changes

2021-01-26 11:07 UTC, in-a-paddy commented on mobile-app-handson/content/docs/app-spec/_index.md
>  weight: 110
あんま重要じゃないけど、 `weight` は `100` 単位で増やしておいた方がいいかも。

2021-01-26 11:07 UTC, in-a-paddy commented on mobile-app-handson/content/docs/app-spec/_index.md
> +ToDoアプリは、ToDoを管理するための次の機能を実現します。
> ToDoアプリは、ToDoを管理するための次の機能を実現します。

なんか、すごい冗長感を感じてしまったんだけど、こんな感じだとクドいかな、、、？

```suggestion
このハンズオンで作成するToDoアプリは、ToDoを管理するための次の機能を実現します。
```

2021-01-26 11:07 UTC, in-a-paddy commented on mobile-app-handson/content/docs/app-spec/_index.md
> + - ToDoを削除できる
消せない、、、、けど、ここには残しておいてもいいかな？

2021-01-26 11:07 UTC, in-a-paddy commented on mobile-app-handson/content/docs/app-spec/_index.md
> +ただし、現在のバージョンではアプリケーションのメモリ上にしか情報をもたないため、認証はダミーとします。
アプリ vs アプリケーション、、、
このドキュメントでは「アプリ」で統一していいんじゃないかな？

```suggestion
ただし、現在のバージョンではアプリのメモリ上にしか情報をもたないため、認証はダミーとします。
```

2021-01-26 11:07 UTC, in-a-paddy commented on mobile-app-handson/content/docs/app-spec/_index.md
> +title: Todoアプリの仕様説明
「仕様説明」 ➡ 「仕様」で充分では？と思ったけど、元のやつが「仕様説明」になってるのか。。。

```suggestion
title: ToDoアプリの仕様
```

2021-01-26 11:07 UTC, in-a-paddy commented on mobile-app-handson/content/docs/app-spec/_index.md
> +# Todoアプリの仕様説明
「仕様説明」 ➡ 「仕様」で充分では？と思ったけど、元のやつが「仕様説明」になってるのか。。。

```suggestion
# ToDoアプリの仕様
```

2021-01-27 00:19 UTC, tani-takanori commented on mobile-app-handson/content/docs/app-spec/_index.md
>  weight: 110
全体に関わることだからweightの調整は小酒さんに渡してからやってもらおうかな...
っていうのとweightってディレクトリより優先されるんかな？（
```
docs/{100 unit}/{10 unit}/{1 unit}  #weight 依存
docs/{100 unit}/{100 unit} / {100 unit} / ** / #階層優先
```

2021-01-27 00:21 UTC, tani-takanori commented on mobile-app-handson/content/docs/app-spec/_index.md
> +ToDoアプリは、ToDoを管理するための次の機能を実現します。
[サービス開発リファレンス](https://fintan-contents.github.io/spa-restapi-handson/todo-spec/)からInjectionされてた...

2021-01-27 00:24 UTC, tani-takanori commented on mobile-app-handson/content/docs/app-spec/_index.md
> +ただし、現在のバージョンではアプリケーションのメモリ上にしか情報をもたないため、認証はダミーとします。
アプリ -> 機能群
アプリケーション -> OS上で動作しているプロセス
で分けようとしてたけど、読んでる人にはわからんからアプリで統一しようかなって思いました

2021-01-27 01:05 UTC, tani-takanori commented on mobile-app-handson/content/docs/app-spec/_index.md
> + - ToDoを削除できる
サービス開発リファレンスも[機能](https://fintan-contents.github.io/spa-restapi-handson/todo-spec/#%E6%A9%9F%E8%83%BD)で[未実装](https://fintan-contents.github.io/spa-restapi-handson/todo-delete/)やけどあったからのこしたんよねー

2021-01-27 01:08 UTC, tani-takanori commented on mobile-app-handson/content/docs/app-spec/_index.md
> + - ToDoを削除できる
とはいえ、サービス開発は演習で、モバイルがエンハンスだとすると補足で `ToDoを削除できる(機能拡張）` にしてもいいかもしれんね

2021-01-27 09:28 UTC, shkozake submitted a review, later dismissed

2021-01-28 04:05 UTC, tani-takanori commented on mobile-app-handson/content/docs/app-spec/_index.md
>  weight: 110
weightは一律対応いれる

2021-01-28 04:05 UTC, tani-takanori commented on mobile-app-handson/content/docs/app-spec/_index.md
> + - ToDoを削除できる
対応しました

2021-01-28 04:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/app-spec/_index.md
>  weight: 110
ほぼメニューの話にしかかかわらないと思うから、それ前提で。上の例だとこうなるはずだと思うんだけど。
あくまで同じ階層の並べ替えに、 `weight` が使われるはず。

- {100 unit}
  - {10 unit}
    - {1 unit}
    - {1000 unit}
  - {100 unit}
    - {100 unit}

2021-01-28 04:49 UTC, in-a-paddy approved these changes

2021-01-29 09:27 UTC, shkozake approved these changes

2021-02-01 02:14 UTC, merged