Feature/handson document
ws-4020/mobile-app-handson pull request #12
Opened 2021-01-26 00:16 UTC by OshitaTatsuya

大枠のドキュメントについて、作成が完了しまいたのでレビューをお願いします。
一部「TODO」となっている部分は調査が必要な部分となり、別途記載します。
環境構築ガイドとして不足している情報がないか？又は、分かりにくい内容となっていないか？
の観点で確認をお願いします。

2021-01-26 01:41 UTC, in-a-paddy requested changes

2021-01-26 01:41 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  - インストールを行う際、chocoコマンドを使用して行います。
何のインストールに使うのかを書いておいた方が良いです。あと、Chocolateyを使わないでインストールすることもできるので、インストールを強制する必要はないと思います。

2021-01-26 01:41 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  - インストールを行う際、brewコマンドを使用して行います。
同上。ChocolateyよりはHomebrewの方がデファクトスタンダードに近いとは思いますが。

2021-01-26 01:41 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築を進めて下さい。
```suggestion
[React Nativeの公式ドキュメント](https://reactnative.dev/docs/environment-setup)を参照し、開発環境を構築してください。
```

2021-01-26 01:41 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  以下で設定を行って下さい。
改行位置の指定は多用しないほうが良いです。

```suggestion
  Android Studioで使用されるSDK及びツール類について、次のように設定してください。
```

2021-01-26 01:41 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      作成方法について、以下で作成して下さい。
```suggestion
      アプリの動作確認にエミュレータを利用します。次のように作成して下さい。
```

2021-01-26 01:41 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +    1. 名前：Pixel 2 を選択し、「次へ」 ボタンを押下
Pixel 2じゃなくてもいいような？古すぎる気がする。

2021-01-26 01:41 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      - ホスト名：tkyproxy.intra.tis.co.jp 又は、oskproxy.intra.tis.co.jp
これ、ただの社内プロキシです。

2021-01-26 01:41 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### proxy設定
NPMのプロキシ設定も必要なはず。

2021-01-26 01:41 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +以下にて、Apple起動を行い、環境が正しく構築出来ていることを確認します。
```suggestion
アプリを起動し、環境が正しく構築出来ていることを確認します。  
```

2021-01-26 01:41 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  | v14.15.1 | [公式サイト](https://nodejs.org/ja/download/) |
HomebrewやChocolateyでは、RNの手順通りに実行するとLTSではなく15系がインストールされると思います。LTSバージョンあるいは14系をインストールする方法をガイドしたほうがいいです。

2021-01-26 01:43 UTC, in-a-paddy commented
文体が全体的に固すぎるような気がします。
[サービス開発リファレンスのハンズオン](https://fintan-contents.github.io/spa-restapi-handson/setup/install/) を見て、もう少し柔らかい文体で書いてもらいたいです。

2021-01-26 01:47 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### proxy設定
あと、CocoaPodsもか

2021-01-26 01:47 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  - インストールを行う際、chocoコマンドを使用して行います。
あと、コマンド名ではなくプロダクト名で書く方が適切だと思います。

2021-01-26 06:23 UTC, shkozake commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築は[ReactNativeの開発環境が構築](https://reactnative.dev/docs/environment-setup)に沿って進めていきますが、一部についてのバージョンを本章記載のものでインストールして下さい。
`ReactNativeの開発環境が構築` の `が` は `を` の間違いではないでしょうか？
以下同様。

2021-01-26 06:27 UTC, shkozake commented on mobile-app-handson/content/docs/setup-env/_index.md
> +本手順では、WindowsとmacOSの両環境での構築を行います。
文章全般として、「〇〇を行います」という文章が目立ちます。
次のように修正したほうが分かりやすいかと思います。

- WindowsとmacOSの両環境での構築を行います。  
         ↓
- WindowsとmacOSの両環境で構築します。 
もしくは
- WindowsとmacOSの両環境の構築手順を示します。 

- インストールを行なっておいて下さい。
         ↓
- インストールしておいて下さい。

2021-01-26 06:33 UTC, shkozake commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### proxy設定
このほかにも、nodeなどのproxy設定などは必要ないでしょうか。

2021-01-26 06:35 UTC, shkozake commented on mobile-app-handson/content/docs/setup-env/_index.md
> +以下にて、Apple起動を行い、環境が正しく構築出来ていることを確認します。
ハンズオンサンプルアプリの動作確認の前に、ハンズオンサンプルアプリのひな型はダウンロードされている前提でしょうか？

2021-01-26 07:39 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### proxy設定
Node.jsとしては必要ないような気がします？ `http_proxy` etc. を環境変数に設定するようにガイドするのがいいかもしれないですが。

2021-01-26 07:40 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### proxy設定
この手順はProxyを利用したネットワークにいる場合の手順なので、Proxyの指定が不要な場合は実施不要とわかるようにしたい。

2021-01-26 07:40 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +アプリ起動に失敗することがあります。
```suggestion
実行した結果、ポート番号(`8081`)が別のプロセスと競合したり、ウイルス対策ソフトにてブロックされることが原因で、アプリの起動に失敗することがあります。  
```

2021-01-26 12:48 UTC, in-a-paddy requested changes

2021-01-26 12:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  | v14.15.1 | [公式サイト](https://nodejs.org/ja/download/releases/) |
既に `14.15.4` が出ているのに、なぜ `14.15.1` をあえてしているのかな、ってなります。

2021-01-26 12:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  | Version 12.3 | [公式サイト](https://developer.apple.com/download/more/?name=Xcode) |
これ、過去バージョンのXcodeじゃないと動かない、ってなったらそっちをインストールしてくださいってなりますかね？

2021-01-26 12:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      - 手動プロキシ設定：チェックを入れる
自動だとダメなんでしたっけ？

2021-01-26 12:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### proxy設定
AndroidエミュレータからProxyを経由して外に出ていくときの話をしないといけなかったですね。

2021-01-26 12:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +アプリ起動に失敗することがあります。
> ウイルス対策ソフトにてブロックされる

このケースってあります？F/Wで外部向けにはブロックされていることが多いですが、ローカルでブロックされたという事象にはあたったことがないので。

2021-01-26 12:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +npm run ios --portポート番号
これ、たぶん動かないです。

2021-01-26 12:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +npm run ios --portポート番号
参考:
iOSでポート変えて動かない件の調査: https://gitlab.com/ws-4020/fintan-contents-draft/mobile-app-crib-notes/-/issues/1
Preprocessor MacrosをPodfileで設定する方法: ググれば色々出てくるけど、この辺とか？https://stackoverflow.com/questions/17908569/specifying-preprocessor-macros-for-a-cocoapod-dependency-without-forking-it

2021-01-26 12:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### Android Studio
「Android Studio」ではないと思う。

2021-01-26 12:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +```
コードブロックの中に分岐があるのはちょっと違和感あります。こんな感じで良いのでは？

```suggestion
* Windows: `netstat -nao | find "ポート番号"`
* macOS: `sudo lsof -i:ポート番号`
```

2021-01-26 12:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +- Xcode
OS設定とかですらなく、パッケージ内のファイルをいじるってのはかなり抵抗がありますね、、、

2021-01-26 12:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +以下に従って、proxyの設定を行います。
この行不要では？

2021-01-26 12:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +settings.jsonへ、以下の内容を記載して下さい。
[VSCodeのドキュメント]((https://code.visualstudio.com/docs/setup/network#_proxy-server-support)見ると、システムのプロキシ設定が使われそうに見えます。実際、自分でもプロキシの設定した記憶はないです。忘れただけかもしれないですが。

出典とかありますか？

2021-01-28 01:44 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  - インストールを行う際、chocoコマンドを使用して行います。
指摘箇所について、React Nativeの公式ドキュメント内に記載があり、過剰な記載な為、削除しました。

2021-01-28 01:46 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  - インストールを行う際、brewコマンドを使用して行います。
指摘箇所について、上記と併せて対応

2021-01-28 02:19 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築を進めて下さい。
指摘箇所について、呼称含めて文脈を修正しました。

2021-01-28 02:20 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  以下で設定を行って下さい。
指摘箇所について、必要最低限のみ意図した改行を使用するよう修正しました。

2021-01-28 02:44 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      作成方法について、以下で作成して下さい。
指摘箇所について、React Nativeの公式ドキュメント内にエミュレータ作成手順が記載されており、内容が重複する為、削除しました。

2021-01-28 02:44 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +    1. 名前：Pixel 2 を選択し、「次へ」 ボタンを押下
指摘箇所について、上記と同様で削除しました。

2021-01-28 02:45 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      - ホスト名：tkyproxy.intra.tis.co.jp 又は、oskproxy.intra.tis.co.jp
指摘箇所について、限定的な内容であった為、修正しました。（プロキシアドレス）

2021-01-28 02:46 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### proxy設定
指摘箇所について、設定理由を記載し、環境変数への設定を追記しました。

2021-01-28 02:54 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +以下にて、Apple起動を行い、環境が正しく構築出来ていることを確認します。
指摘箇所について、本ドキュメントは基本公式に沿って、環境を構築し、結果を確認するものになります。
ですので、ハンズオンサンプルアプリの動作確認ついて、記載場所の誤りの為、削除しました。
（なので、前提事項にハンズオンサンプルアプリがクローンされていることは記載しておりません。）

2021-01-28 02:55 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  | v14.15.1 | [公式サイト](https://nodejs.org/ja/download/) |
指摘箇所について、LTSバージョンをインストールする内容に修正しました。

2021-01-28 05:31 UTC, in-a-paddy requested changes

2021-01-28 05:31 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  Node.jsのバージョンは、LTS（推奨版）を使用します。[公式サイト](https://nodejs.org/ja/download/)よりダウンロードし、インストールしてください。
推奨という意味ではないと思います。

```suggestion
  Node.jsのバージョンは、LTS（長期サポート版）を使用します。[公式サイト](https://nodejs.org/ja/download/)よりダウンロードし、インストールしてください。  
```

2021-01-28 05:31 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +ReactNative開発を行うための環境構築手順となります。本手順では、WindowsとmacOSの両環境での構築を行います。
```suggestion
ReactNative開発を行うための環境構築手順となります。本手順では、WindowsとmacOSの両環境での構築方法を説明します。
```

2021-01-28 05:31 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  Node.jsのバージョンは、LTS（推奨版）を使用します。[公式サイト](https://nodejs.org/ja/download/)よりダウンロードし、インストールしてください。
公式手順ではChocolateyを使ってるので、「Chocolateyでインストールする場合は `nodejs.install` ではなく `node-lts` をインストールしてください」とかの説明にした方がわかりやすいと思います。

2021-01-28 07:39 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +本手順では、WindowsとmacOSの両環境での構築を行います。
指摘箇所について、分かりやすい文章となることを目指し、修正しました。

2021-01-28 07:59 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築は[ReactNativeの開発環境が構築](https://reactnative.dev/docs/environment-setup)に沿って進めていきますが、一部についてのバージョンを本章記載のものでインストールして下さい。
指摘箇所について、文章の修正及び、箇条書きの記載を修正しました。

2021-01-28 08:00 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      ※既にエミュレータを作成している場合は、「仮想デバイスの作成」
指摘箇所について、React Nativeの公式サイトと内容が重複していたので削除しました。

2021-01-28 08:01 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### proxy設定
指摘箇所について、設定が必要なタイミングが明確になるよう修正しました。

2021-01-28 08:06 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  | v14.15.1 | [公式サイト](https://nodejs.org/ja/download/releases/) |
指摘箇所について、14.15.1にあえて固執する理由はないです。（初期構築時（2020/11）のバージョンがこれだったのでその流れのままでした。）
基本、最新版で問題ないと考えているので、記載を修正しました。

2021-01-28 08:07 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  | Version 12.3 | [公式サイト](https://developer.apple.com/download/more/?name=Xcode) |
指摘箇所について、こちらもバージョンの制約はないです。
また、React Nativeの公式サイトと内容が重複していたので削除しました。

2021-01-28 08:22 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### Android Studio
指摘事項について、proxy経由での通信の説明を追記。及び、ポート指定の実行について、修正

2021-01-28 08:25 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +```
指摘箇所について、記載を修正

2021-01-28 09:56 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +- Xcode
指摘箇所について、環境変数へproxy設定を行う手順を追記した為、削除します。

2021-01-28 09:57 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +以下に従って、proxyの設定を行います。
指摘箇所について、別対応で削除しました。

2021-01-28 09:57 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +settings.jsonへ、以下の内容を記載して下さい。
指摘箇所について、別対応で削除しました。

2021-01-28 10:10 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  Node.jsのバージョンは、LTS（推奨版）を使用します。[公式サイト](https://nodejs.org/ja/download/)よりダウンロードし、インストールしてください。
指摘箇所について、説明内容の修正とインストール時に使用するコマンドを追記しました。

2021-01-28 11:06 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +ReactNative開発を行うための環境構築手順となります。本手順では、WindowsとmacOSの両環境での構築を行います。
指摘箇所について、記載内容を修正しました。

2021-01-28 11:07 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      - 手動プロキシ設定：チェックを入れる
指摘箇所について、全体的にproxy設定の内容を見直した為、削除しました。

2021-01-29 05:06 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +アプリ起動に失敗することがあります。
指摘箇所について、記載内容の見直しを行い、修正しました。

2021-01-29 05:48 UTC, in-a-paddy submitted a review, later dismissed

2021-01-29 05:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +    2. アプリ起動: `npx react-native run-ios --port ポート番号`
react-native-cli の話も足しておきましょう。

2021-01-29 05:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  Node.jsと一緒にOpenJDKをインストールするので、上記でインストール後、[公式サイト](http://jdk.java.net)よりOpneJDKをダウンロードし、インストールしてください。
Node.js 15系でも動くようになったみたいなので、ここは不要になるかな、と。

2021-01-29 05:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  本IDEがなくても、環境構築は進められますが、ハンズオンアプリを作成するに当たって、幾つか便利なプラグインも紹介しているので利用をお勧めします。
こっちの書き方をパクらせてもらっていいと思います。

https://fintan-contents.github.io/spa-restapi-handson/setup/install/#visual-studio-code%E3%81%AE%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB

2021-01-29 05:48 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      - NDK(Side by side)
これ、多分ですが必須ではないですね。

2021-01-29 05:50 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### proxy設定
Gradleの設定は抜けてますね。
あと、macOSでの動作確認が必要、と。

2021-01-29 05:51 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  | v14.15.1 | [公式サイト](https://nodejs.org/ja/download/) |
15系でも動作することが確認できたので、こいつは取り下げです。

2021-01-29 07:04 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +アプリ起動に失敗することがあります。
ウイルス対策ソフトでブロックされることはないけど、Firewallではありえるかな？
明確に拒否するパターンなのでわかると思うけど

2021-01-29 07:26 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築は[React Nativeの公式ドキュメント](https://reactnative.dev/docs/environment-setup)（以降、「RN環境構築手順」と呼称）を参照して進めてください。一部についてはRN環境構築手順の手順で動作しない事があるため、**必ずRN環境構築実施前に**以下記載があるものは本ドキュメントの内容で構築してください。
（このドキュメントである）「初期構築ガイド」と（リンク先の）「React Nativeの公式ドキュメント」はどちらもRN環境構築手順といえば当てはまる気がするので、
`以降、「公式ガイド」` のほうが個人的にわかりやすいかなと思いました。

2021-01-29 07:55 UTC, tani-takanori requested changes

2021-01-29 07:55 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +ReactNative開発を行うための環境構築手順となります。本手順では、WindowsとmacOSの両環境での構築方法を説明します。
```suggestion
React Nativeでアプリケーションを開発するための環境構築手順です。本手順では、WindowsとmacOSの両環境での構築方法を説明します。
```

2021-01-29 08:10 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  * インストールコマンド: `choco install -y node-lts.install openjdk8`
なんでjava8なんでしょう？
※私はjava11でやっていたので意図があれば知りたい

2021-01-29 08:13 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築は[React Nativeの公式ドキュメント](https://reactnative.dev/docs/environment-setup)（以降、「RN環境構築手順」と呼称）を参照して進めてください。一部についてはRN環境構築手順の手順で動作しない事があるため、**必ずRN環境構築実施前に**以下記載があるものは本ドキュメントの内容で構築してください。
> 以下記載があるものは本ドキュメントの内容で構築してください。
以下がどこまでかがわからないので、参照すべきものを箇条書きにしたほうがいいと思います。
ドキュメントを読みながらDiffを取るのは大変なので...

もし意図しているものが「次のOSごとのインストール」なのであれば「以下」ではなく、「次の〜」が良いと思います。

2021-01-29 08:17 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +    ~/.bash_profileへ以下を追記してください。
```suggestion
   ` ~/.bash_profile` へ以下を追記してください。
```

2021-01-29 08:18 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      export https_proxy=https://プロキシアドレス:ポート番号
TETRAってhttps_proxyにつなぐときhttps://tky〜でつなげたっけ？

2021-02-01 03:58 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### proxy設定
指摘箇所について、Gradleのproxy設定を追記しました。
（動作確認は端末調整を行い、別途対応します。）

2021-02-01 04:25 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +    2. アプリ起動: `npx react-native run-ios --port ポート番号`
react-native-cliについて、動作確認時の参照事項として追記しまいた。

2021-02-01 04:25 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  Node.jsと一緒にOpenJDKをインストールするので、上記でインストール後、[公式サイト](http://jdk.java.net)よりOpneJDKをダウンロードし、インストールしてください。
事前準備の中からnodeに関連する内容を削除しました。

2021-02-01 04:26 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +  本IDEがなくても、環境構築は進められますが、ハンズオンアプリを作成するに当たって、幾つか便利なプラグインも紹介しているので利用をお勧めします。
vscodeのインストール手順について、参照先の内容で修正しました。

2021-02-01 04:28 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      - NDK(Side by side)
NDKをインストールしない状態でサンプルアプリの動作確認を行い、正常に動作した為、手順からNDKをインストールする旨を削除しました。

2021-02-01 04:42 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築は[React Nativeの公式ドキュメント](https://reactnative.dev/docs/environment-setup)（以降、「RN環境構築手順」と呼称）を参照して進めてください。一部についてはRN環境構築手順の手順で動作しない事があるため、**必ずRN環境構築実施前に**以下記載があるものは本ドキュメントの内容で構築してください。
RN環境構築手順について、指しているドキュメントが曖昧な為、"React Nativeの公式ドキュメント"へ修正しました。
また、事前準備について参照すべきものを明確にする為、文言の修正（本章を参照）を併せて実施しました。

2021-02-01 04:44 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +ReactNative開発を行うための環境構築手順となります。本手順では、WindowsとmacOSの両環境での構築方法を説明します。
指摘箇所について、記載内容の見直しを行い、修正しました。

2021-02-01 05:05 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +    ~/.bash_profileへ以下を追記してください。
指摘箇所について、コードブロック形式に修正しました。

2021-02-01 06:54 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      export https_proxy=https://プロキシアドレス:ポート番号
指摘箇所について、設定値を誤りの為、"http://～"へ修正しました。

2021-02-01 06:59 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +    構成 > SDKマネージャー > 外観 & 振る舞い > システム設定 > Android SDK > SDKツール
指摘箇所について、公式サイトと内容が重複していた為、削除しました。

2021-02-01 06:59 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +    - Google APIs Intel x86 Atom System Image
こちらも同様で、公式サイトと内容が重複していた為、削除しました。

2021-02-01 07:24 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +proxy環境下で環境構築を進める場合、一部のツール及び、動作確認時に使用するエミュレータについて、proxy経由での通信が発生する為、設定が必要となります。以下を参照してそれぞれの設定を実施してください。
情報共有ありがとうございます。必要なproxy設定を追記しました。

2021-02-01 07:32 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築は[React Nativeの公式ドキュメント](https://reactnative.dev/docs/environment-setup)（以降、「RN環境構築手順」と呼称）を参照して進めてください。一部についてはRN環境構築手順の手順で動作しない事があるため、**必ずRN環境構築実施前に**以下記載があるものは本ドキュメントの内容で構築してください。
指摘箇所について、参照先を明確にする目的で追記しました。

2021-02-01 07:33 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築は[React Nativeの公式ドキュメント](https://reactnative.dev/docs/environment-setup)（以降、「RN環境構築手順」と呼称）を参照して進めてください。一部についてはRN環境構築手順の手順で動作しない事があるため、**必ずRN環境構築実施前に**以下記載があるものは本ドキュメントの内容で構築してください。
指摘箇所について、呼称をReact Nativeの公式ドキュメントへ修正しました。

2021-02-01 07:41 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築は[React Nativeの公式ドキュメント](https://reactnative.dev/docs/environment-setup)（以降、「RN環境構築手順」と呼称）を参照して進めてください。一部についてはRN環境構築手順の手順で動作しない事があるため、**必ずRN環境構築実施前に**以下記載があるものは本ドキュメントの内容で構築してください。
まずは、↓で対応を決めたいです。
https://github.com/ws-4020/rn-spoiler/issues/40

2021-02-01 07:55 UTC, tani-takanori requested changes

2021-02-01 07:55 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      * macOS: `/Users/ooshitatatsuya/.gradle/gradle.properties`
```suggestion
      * Windows: `C:\Users\%USERNAME%\.gradle\gradle.properties`
      * macOS: `~/.gradle/gradle.properties`  
```
Windowsのほうはもう少しスマートにできるかもしれませんが、`以下を参照してください`（例と記載しない）で大下さんのパスで示すのは不適切だと思います。

2021-02-01 08:03 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +- ポート番号のロック及び、競合
プロジェクトを作成 -> 動作確認のステップになると思うので躓く順番を考慮すると
`react native cli` と言及する順番が逆のほうが良いと思いますがどうでしょうか？

2021-02-01 08:18 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +上記までで事前準備は完了です。[React Nativeの公式ドキュメント](https://reactnative.dev/docs/environment-setup)を参照し、環境構築を進めてください。一部の設定等について、以下に補足事項を記載しています。React Nativeの公式ドキュメントと併せて以下の補足事項も参照しながら進めてください。
公式の手順で作成したProjectはどうするんだろう？
削除してもらったほうがいいと思うけど

2021-02-01 08:19 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +アプリを実行した結果、ポート番号が別プロセスと競合したり、ウイルス対策ソフトにてロックされていることが原因で、アプリ起動に失敗することがあります。ポート番号の利用状況を確認し、必要に応じてポート番号を変更してください。
ポート番号を明示してないのは理由ありますか？（失敗したときにログ見ろなんですかね？）

2021-02-01 08:29 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築は[React Nativeの公式ドキュメント](https://reactnative.dev/docs/environment-setup)を参照して環境構築を進めてください。構築を進める前に必要なもの（React Nativeの公式ドキュメントに記載されていないもの）を本章にまとめているので、**React Nativeの公式ドキュメントを参照する前に**対応してください。
(このドキュメントの使い方の想定として公式ドキュメントと一緒に見るのか、このドキュメントの内容を理解してから見るのかで変わると思いますが) 一緒に見ることが想定されるのであれば別タブで開いてほしいです。

2021-02-01 09:48 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +- ポート番号のロック及び、競合
指摘箇所について、躓きやすさという意味でポートの方が高いと思っており、今の順序から変更しないでおこうと思います。
react native cliは私が他の手順を参照した際にインストールしてしまったものであり、今回の手順を参照する中では
再現率は低いと考えています。

2021-02-01 09:50 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +アプリを実行した結果、ポート番号が別プロセスと競合したり、ウイルス対策ソフトにてロックされていることが原因で、アプリ起動に失敗することがあります。ポート番号の利用状況を確認し、必要に応じてポート番号を変更してください。
ポート番号を明示していないのは、状況によって競合したりするポート番号は違うと考えているためです。

2021-02-01 10:00 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +アプリを実行した結果、ポート番号が別プロセスと競合したり、ウイルス対策ソフトにてロックされていることが原因で、アプリ起動に失敗することがあります。ポート番号の利用状況を確認し、必要に応じてポート番号を変更してください。
React Native（というかMetro Bundler）がデフォルトで使うポートは `8081` なので、そのことは書いておいてあげたほうが良いと思います。

```suggestion
React Nativeでは、アプリを実行するためにデフォルトでは`8081`番ポートを利用します。

このポートが別プロセスと競合しているとアプリの実行に失敗してしまいます。こういった場合は利用するポートを変更してください。
```

2021-02-01 10:21 UTC, in-a-paddy requested changes

2021-02-01 10:21 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +## 動作確認
トラブルシュート系の話だと思うので、タイトルもそうしたほうが良いと思います。

```suggestion
## トラブルシュート
```

2021-02-01 10:21 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +- ポート番号のロック及び、競合
```suggestion
### トップ画面でJavaScriptがロードできないというエラーが発生する
```

2021-02-02 02:18 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      * macOS: `/Users/ooshitatatsuya/.gradle/gradle.properties`
指摘箇所について、記載誤りのため修正しました。

2021-02-02 02:24 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +- ポート番号のロック及び、競合
指摘箇所ついて、リストから見出し形式へ変更し、タイトル部分も合わせて修正しました。

2021-02-02 02:44 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +アプリを実行した結果、ポート番号が別プロセスと競合したり、ウイルス対策ソフトにてロックされていることが原因で、アプリ起動に失敗することがあります。ポート番号の利用状況を確認し、必要に応じてポート番号を変更してください。
指摘事項について、指摘内容及び、サンプルを元に修正しました。
サンプルの提供ありがとうございました。

2021-02-02 02:55 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +## 動作確認
指摘箇所について、タイトルを修正しました。また併せて説明内容も修正しました。

2021-02-02 04:46 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      * Windows: `C:\Users\tie307112\.gradle\gradle.properties`
対象箇所について、記述改善を行い修正

2021-02-02 04:46 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      * macOS: `/Users/ooshitatatsuya/.gradle/gradle.properties`
対象箇所について、記述改善を行い修正

2021-02-02 04:46 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +アプリを実行した結果、ポート番号が別プロセスと競合したり、ウイルス対策ソフトにてロックされていることが原因で、アプリ起動に失敗することがあります。ポート番号の利用状況を確認し、必要に応じてポート番号を変更してください。
対象箇所について、記述改善を行い修正

2021-02-02 04:46 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +    macOSの場合、Metro Bundlerをポート番号指定で起動した後にシミュレータ起動を行います。
対象箇所について、記述改善を行い修正

2021-02-02 04:46 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +グローバルにインストールされているパッケージは`npm ls -g --depth=0`で確認することができます。 実行結果に react-native-cli が含まれている場合は、 **必ずアンインストール**してください。 `npm uninstall -g react-native-cli` でアンインストールできます。
対象箇所について、記述改善を行い修正

2021-02-02 05:39 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +アプリ起動に失敗することがあります。
本件について、[issu](https://github.com/ws-4020/mobile-app-handson/issues/16)を作成しました。

2021-02-02 05:44 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築は[React Nativeの公式ドキュメント](https://reactnative.dev/docs/environment-setup)（以降、「RN環境構築手順」と呼称）を参照して進めてください。一部についてはRN環境構築手順の手順で動作しない事があるため、**必ずRN環境構築実施前に**以下記載があるものは本ドキュメントの内容で構築してください。
本件について、[issu](https://github.com/ws-4020/mobile-app-handson/issues/17)を作成しました。

2021-02-02 08:38 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +上記までで事前準備は完了です。[React Nativeの公式ドキュメント](https://reactnative.dev/docs/environment-setup)を参照し、環境構築を進めてください。一部の設定等について、以下に補足事項を記載しています。React Nativeの公式ドキュメントと併せて以下の補足事項も参照しながら進めてください。
本件、個別で確認しましたが、ハンズオンを進める中で手順に沿って、Projectを作成するとのことなので、
作成したProjectを削除する説明は一旦追記しないこととします。

2021-02-02 08:45 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築は[React Nativeの公式ドキュメント](https://reactnative.dev/docs/environment-setup)を参照して環境構築を進めてください。構築を進める前に必要なもの（React Nativeの公式ドキュメントに記載されていないもの）を本章にまとめているので、**React Nativeの公式ドキュメントを参照する前に**対応してください。
本件、一旦[issu#18](https://github.com/ws-4020/mobile-app-handson/issues/18)を作成しました。

2021-02-03 04:30 UTC, tani-takanori approved these changes

2021-02-03 16:37 UTC, in-a-paddy approved these changes

2021-02-03 16:38 UTC, merged