コンポーネントのリストのサンプルとその他
ws-4020/mobile-app-handson pull request #21
Opened 2021-02-04 08:22 UTC by shkozake

## ✅ What's done

- [ ] FlatListとSectionListのサンプルコードを追加しました
- [ ] React Native Elementsの説明を追加しました
- [ ] コンポーネントの最後に「コラム」を追加しあｍした。

## Devices

- [ ] 動作確認に利用したデバイスにチェックをつけてください
- [ ] iOS
  - [ ] シミュレータ (iPhone Xs/iOS 14)
  - [ ] 実機 (iPhone 8/iOS 14)
- [ ✅] Android
  - [ ✅] エミュレータ (Pixel 3a/Android 11)
  - [ ] 実機 (Pixel 3a/Android 11)

## Other (messages to reviewers, concerns, etc.)

コラムが余分なら削除します。

2021-02-04 08:58 UTC, tani-takanori requested changes

2021-02-04 08:58 UTC, tani-takanori commented on mobile-app-handson/content/docs/before-impl-app/react-native-basics/components/lists/_index.md
> +リストはScrollViewsに似ていますが、要素をリサイクルして再描画を減らすことでパフォーマンス向上するよう最適化されています。
```suggestion
リストはScrollViewに似ていますが、要素をリサイクルして再描画を減らすことでパフォーマンス向上するよう最適化されています。
```

2021-02-04 08:58 UTC, tani-takanori commented on mobile-app-handson/content/docs/before-impl-app/react-native-basics/components/lists/_index.md
> +リストはScrollViewsに似ていますが、要素をリサイクルして再描画を減らすことでパフォーマンス向上するよう最適化されています。
あれ？あえて複数形にしてます？？

2021-02-04 09:06 UTC, tani-takanori requested changes

2021-02-04 09:06 UTC, tani-takanori commented on mobile-app-handson/content/docs/before-impl-app/react-native-basics/components/lists/flat-list.md
> +`ScrollViews`同様、水平方向または垂直方向にスクロールできます。
```suggestion
`ScrollView`同様、水平方向または垂直方向にスクロールできます。
```

2021-02-04 09:06 UTC, tani-takanori commented on mobile-app-handson/content/docs/before-impl-app/react-native-basics/components/lists/flat-list.md
> +`item.key`がデフォルトのIDとして用いられますが、`keykeyExtractor`に関数を渡すことで別のID値を指定できます。
```suggestion
`item.key`がデフォルトのIDとして用いられますが、`keyExtractor`に関数を渡すことで別のID値を指定できます。
```

2021-02-04 09:06 UTC, tani-takanori commented on mobile-app-handson/content/docs/before-impl-app/react-native-basics/components/lists/section-list.md
> +`SectionLists`は`FlatList`に似ており、行区切りのセクションヘッダーを持つことができます。
```suggestion
`SectionList`は`FlatList`に似ており、行区切りのセクションヘッダーを持つことができます。
```

2021-02-04 10:21 UTC, in-a-paddy approved these changes

2021-02-04 10:21 UTC, in-a-paddy commented on mobile-app-handson/content/docs/before-impl-app/react-native-basics/components/lists/_index.md
> +大量のデータを画面に表示する場合、`FlatList`および`SectionList`の使用が推奨されます。
感覚的にはORですが、あってますか？

```suggestion
大量のデータを画面に表示する場合、`FlatList`または`SectionList`の使用が推奨されます。
```

2021-02-04 10:21 UTC, in-a-paddy commented on mobile-app-handson/content/docs/before-impl-app/react-native-basics/components/lists/section-list.md
> +`SectionList`は`FlatList`に似ており、行区切りのセクションヘッダーを持つことができます。
たぶん「表示されるコンテンツのみを描画」関連のところが「似ている」ってことだと思ったので、↓みたいな感じで少し説明を足してみました。どうでしょう？

```suggestion
`SectionList`は`FlatList`と同じように表示されるコンテンツのみを描画し、さらに行区切りのセクションヘッダーを持つことができます。
```

2021-02-05 04:45 UTC, shkozake commented on mobile-app-handson/content/docs/before-impl-app/react-native-basics/components/lists/_index.md
> +大量のデータを画面に表示する場合、`FlatList`および`SectionList`の使用が推奨されます。
ORであってます。suggestionでcommitしました。

2021-02-05 04:46 UTC, shkozake commented on mobile-app-handson/content/docs/before-impl-app/react-native-basics/components/lists/section-list.md
> +`SectionList`は`FlatList`に似ており、行区切りのセクションヘッダーを持つことができます。
こちらのほうが分かりやすいですね。suggestionでcommitしました。

2021-02-05 04:47 UTC, shkozake commented on mobile-app-handson/content/docs/before-impl-app/react-native-basics/components/lists/_index.md
> +リストはScrollViewsに似ていますが、要素をリサイクルして再描画を減らすことでパフォーマンス向上するよう最適化されています。
複数形は間違いでした。suggestionでcommitしました。

2021-02-05 04:47 UTC, shkozake commented on mobile-app-handson/content/docs/before-impl-app/react-native-basics/components/lists/flat-list.md
> +`ScrollViews`同様、水平方向または垂直方向にスクロールできます。
複数形は間違いでした。suggestionでcommitしました。

2021-02-05 04:47 UTC, shkozake commented on mobile-app-handson/content/docs/before-impl-app/react-native-basics/components/lists/flat-list.md
> +`item.key`がデフォルトのIDとして用いられますが、`keykeyExtractor`に関数を渡すことで別のID値を指定できます。
打ち間違いでした。suggestionでcommitしました。

2021-02-05 04:48 UTC, shkozake commented on mobile-app-handson/content/docs/before-impl-app/react-native-basics/components/lists/section-list.md
> +`SectionLists`は`FlatList`に似ており、行区切りのセクションヘッダーを持つことができます。
複数形は間違いでした。suggestionでcommitしました。

2021-02-05 04:50 UTC, tani-takanori approved these changes

2021-02-05 04:51 UTC, in-a-paddy approved these changes

2021-02-05 04:51 UTC, merged