update #17 text fix
ws-4020/mobile-app-handson pull request #22
Opened 2021-02-04 08:23 UTC by OshitaTatsuya

## 💣 BREAKING CHANGES 💣
- ReactNativeでの開発に必要なアプリケーションが既にグローバル環境内にインストールされているかを確認する項目を追加 
- グローバル環境のチェックに合わせて、周辺の文脈を修正

## ✅ What's done
- [x] 確認対象とバージョンを表景色に纏め、追加
- [x] 既存の文脈（環境構築時、既にインストールしているものは再インストール不要）の修正

## Tests
- [x] プレビュー表示を行い、全体の崩れ等がないかのチェック
- [x] ローカルでlintを実施

## Other (messages to reviewers, concerns, etc.)
なし

2021-02-04 10:27 UTC, in-a-paddy approved these changes

2021-02-04 10:27 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +ReactNativeでアプリケーションを開発する為の環境構築手順です。WindowsとmacOSの両環境での構築方法を説明します。
```suggestion
React Nativeでアプリケーションを開発する為の環境構築手順です。WindowsとmacOSの両環境での構築方法を説明します。
```

2021-02-04 10:27 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築を進める前にReactNativeでの開発に必要なアプリケーションが既にグローバル環境内にインストールされているかを確認します。既にインストールされている（バージョンが指定のもの以上を含む）場合、再インストール不要です。まずはインストール状況について確認してください。
```suggestion
環境構築を進める前にReact Nativeでの開発に必要なアプリケーションが既にグローバル環境内にインストールされているかを確認します。既にインストールされている（バージョンが指定のもの以上を含む）場合、再インストール不要です。まずはインストール状況について確認してください。
```

2021-02-04 10:27 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +| 共通 | Android Studio | 指定なし | IDEが、インストールされているかを確認 |
一番ハマるのが環境変数の設定だと思うので、コマンドラインから `emulator` とか `abd` とかのコマンドを実行できることは確認してもらったほうがいいかも、、、

2021-02-04 10:27 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +| 共通 | Node.js | v10.x.x以上 | コマンドラインで`node -v`を実行し、エラーメッセージが表示されたらインストールが必要 |
表示されるバージョンの確認についても触れたほうが良さそう？

2021-02-05 07:10 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +ReactNativeでアプリケーションを開発する為の環境構築手順です。WindowsとmacOSの両環境での構築方法を説明します。
指摘箇所の文言について、修正しました。（ReactNative→React Native）

2021-02-05 07:11 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築を進める前にReactNativeでの開発に必要なアプリケーションが既にグローバル環境内にインストールされているかを確認します。既にインストールされている（バージョンが指定のもの以上を含む）場合、再インストール不要です。まずはインストール状況について確認してください。
指摘箇所の文言（ReactNative→React Native）と文脈を修正しました。

2021-02-05 07:12 UTC, in-a-paddy requested changes

2021-02-05 07:12 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +| 共通 | Android Studio | 指定なし | IDEが、インストールされているかを確認 |
指摘箇所について、Android SDKのツール類が使用出来ることを確認する内容と、使用出来なかった場合（emulator）の対処方法を追記しました。

2021-02-05 07:13 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +| 共通 | Node.js | v10.x.x以上 | コマンドラインで`node -v`を実行し、エラーメッセージが表示されたらインストールが必要 |
個々のバージョンの確認（方法とバージョン指定）について、記載しました。

2021-02-05 07:32 UTC, in-a-paddy requested changes

2021-02-05 07:32 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +| emulator | コマンドラインで`emulator`を実行し、エラーが表示された場合、Android SDKのインストールまたは、環境変数（Windowsの環境変数設定ついては、[環境変数の設定について](http://localhost:1313/docs/setup-env/#windows-android-sdk-emulator%e3%83%84%e3%83%bc%e3%83%
```suggestion
| emulator | コマンドラインで`emulator`を実行し、エラーが表示された場合、Android SDKのインストールまたは、環境変数（Windowsの環境変数設定ついては、[環境変数の設定について](#windows-android-sdk-emulator%e3%83%84%e3%83%bc%e3%83%ab%e3%81%ae%e7%92%b0%e5%a2%83%e5%a4%89%e6%95%b0%e8%a8%ad%e5%ae%9a%e3%81%ab%e3%81%a4%e3%81%84%e3%81%a6)を参照）を設定してください 
```

2021-02-05 08:26 UTC, tani-takanori requested changes

2021-02-05 08:26 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +| macOS | Xcode | IDEが、インストールされているかを確認 | Xcodeを起動し、必要バージョン（`12.x`）以降のバージョンであれば、OK。 例：`Version 12.3(12C33)"`と出力された場合、OK | ― |
```suggestion
### **必要なアプリケーションとバージョン**
| 環境 | 名称 | インストール状況の確認 | バージョンの確認 | 
| :--- | :--- | :--- | :--- |
| 共通 | Node.js | コマンドラインで`node -v`を実行し、エラーが表示された場合、インストールが必要 | 左記のコマンド実行結果、必要バージョン（`v10.x.x`）以降であれば、OK。 例：`v14.15.1`と出力された場合、OK |
| 共通 | Open Java Development Kit | コマンドラインで`java -version`を実行し、エラーが表示された場合、インストールが必要 | 左記のコマンド実行結果、必要バージョン（`1.8.x`）以降のバージョンであれば、OK。 例：`openjdk version "1.8.0_275"`と出力された場合、OK |
| 共通 | Android Studio | [Android SDK](#android-sdk%e4%b8%bb%e3%81%aa%e5%88%a9%e7%94%a8%e3%83%84%e3%83%bc%e3%83%ab)を参照し、インストールされているかを確認 | ― |
| macOS | Watchman | コマンドラインで`watchman -v`を実行し、エラーが表示された場合、インストールが必要 | ― |
| macOS | CocoaPods | コマンドラインで`pod --version`を実行し、エラーが表示された場合、インストールが必要 | ― |
| macOS | Xcode | IDEが、インストールされているかを確認 | Xcodeを起動し、必要バージョン（`12.x`）以降のバージョンであれば、OK。 例：`Version 12.3(12C33)"`と出力された場合、OK |
```

`Android Studio(SDK)` だけその他でガイドしていますが、リンク先でも確認しているのでそちらにリンクを飛ばしてあげて、検証方法を記載しませんか？

2021-02-05 08:43 UTC, tani-takanori requested changes

2021-02-05 08:43 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +React Nativeでアプリケーションを開発する為の環境構築手順です。環境構築を進める前にReact Nativeでの開発に必要なアプリケーションが既にグローバル環境内にインストールされているか確認します。既にインストール済でバージョンが指定以降の場合、該当のアプリケーションについては、再インストールは不要です。まずは自身の環境について確認してください。
```suggestion
# 環境構築
React Nativeでアプリケーションを開発する為の環境構築手順です。環境構築を進める前に必要なツールが既にインストールされているか確認してください。必要なバージョンでインストールしている場合は該当のツールのインストール作業は不要です。（バージョンを満たしていない場合はアップデートしてください。）
```

2021-02-05 09:03 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### **必要なアプリケーションとバージョン**
ここで`react-native-cli`がインストール **されていないこと** を確認してもらってもいいかなと思います。

2021-02-08 02:01 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +必要なアプリケーションとバージョンの確認方法について、以下に纏めているので、確認してください。
改行が足りてなくて表形式のViewから消えてますね

2021-02-08 02:41 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +環境構築を進める前にReactNativeでの開発に必要なアプリケーションが既にグローバル環境内にインストールされているかを確認します。既にインストールされている（バージョンが指定のもの以上を含む）場合、再インストール不要です。まずはインストール状況について確認してください。
日常的に使用しない為、"自身の環境"へ汎用的かつわかりやすい言葉へ修正しました

2021-02-08 02:42 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +| emulator | コマンドラインで`emulator`を実行し、エラーが表示された場合、Android SDKのインストールまたは、環境変数（Windowsの環境変数設定ついては、[環境変数の設定について](http://localhost:1313/docs/setup-env/#windows-android-sdk-emulator%e3%83%84%e3%83%bc%e3%83%
リンクの件、誤っていた為修正しました

2021-02-08 02:49 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### **必要なアプリケーションとバージョン**
事前確認の対象に`react-native-cli`を追加し、インストールされている場合はアンインストールするよう記載しました

2021-02-08 03:04 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +| macOS | Xcode | IDEが、インストールされているかを確認 | Xcodeを起動し、必要バージョン（`12.x`）以降のバージョンであれば、OK。 例：`Version 12.3(12C33)"`と出力された場合、OK | ― |
分かりにくい記載の為、内容の見直しと修正を行いました。リンク先ではツール単位(adb等)の確認方法のみを記載したかった為、その他不要な内容（インストール確認）を削除しました。」

2021-02-08 04:04 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +React Nativeでアプリケーションを開発する為の環境構築手順です。環境構築を進める前にReact Nativeでの開発に必要なアプリケーションが既にグローバル環境内にインストールされているか確認します。既にインストール済でバージョンが指定以降の場合、該当のアプリケーションについては、再インストールは不要です。まずは自身の環境について確認してください。
指摘箇所について、内容の見直しを行い修正しました。

2021-02-08 04:04 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +必要なアプリケーションとバージョンの確認方法について、以下に纏めているので、確認してください。
openJDKを確認対象として、追加（修正）しました。

2021-02-08 04:05 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +必要なアプリケーションとバージョンの確認方法について、以下に纏めているので、確認してください。
テーブル形式の場合、環境によって見にくいとの指摘を受けて、記載と形式を修正しました

2021-02-08 04:51 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +| emulator | コマンドラインで`emulator`を実行し、エラーが表示された場合、Android SDKのインストールまたは、環境変数（Windowsの環境変数設定ついては、[環境変数の設定について](http://localhost:1313/docs/setup-env/#windows-android-sdk-emulator%e3%83%84%e3%83%bc%e3%83%
意図としては、検証やエミュレータ利用時の設定変更等を行うときに必要となるツール類を導入してもらいためです。
導入背景と各ツールの説明がなかったので追記しました。

2021-02-08 10:03 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +| emulator | コマンドラインで`emulator`を実行し、エラーが表示された場合、Android SDKのインストールまたは、環境変数（Windowsの環境変数設定ついては、[環境変数の設定について](http://localhost:1313/docs/setup-env/#windows-android-sdk-emulator%e3%83%84%e3%83%bc%e3%83%
WindowsでもmacOSでも`$ANDROID_HOME/platform-tools`は`Path`に追加するように書かれているので、`adb`の確認はしておきましょう。（ないときはPATHを設定してくださいね、と）
`emulator`に関しては、Windowsの手順では含まれていない（し、自分のmacOS環境でもPATH含めていなかった）ので、確認不要にしてしまいましょう。

2021-02-08 23:56 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +| emulator | コマンドラインで`emulator`を実行し、エラーが表示された場合、Android SDKのインストールまたは、環境変数（Windowsの環境変数設定ついては、[環境変数の設定について](http://localhost:1313/docs/setup-env/#windows-android-sdk-emulator%e3%83%84%e3%83%bc%e3%83%
指摘箇所について、platform-toolsを確認対象とする内容に修正。
また、emulatorについては確認対象から削除（環境変数の設定手順も併せて削除）

2021-02-09 00:38 UTC, in-a-paddy requested changes

2021-02-09 00:38 UTC, in-a-paddy commented on mobile-app-handson/content/docs/setup-env/_index.md
> +        `C:\Users\%USERNAME%\AppData\Local\Android\Sdk\platform-tools`
これ、Windowsしか考慮できてないですよね？

```suggestion
        `% LOCALAPPDATA%\Android\Sdk\platform-tools`
```

2021-02-09 02:07 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +        `C:\Users\%USERNAME%\AppData\Local\Android\Sdk\platform-tools`
指摘箇所について、Windows側のパス修正と、macOS側のpathへの追加設定を追加しました。

2021-02-09 02:46 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +    - **インストール状況と環境変数の確認**<br>
説明内容を見直し、文字列長制限内に収まるよう修正

2021-02-09 02:46 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      確認はAndroid StudioのSDK Managerを参照して確認します。Android Studioを起動し、`Configure > SDK Manager > Appearance & Behavior > System Setting > Android SDK`まで遷移し、`SDK Tools`タブを選択してください。タブ内で`Android SDK Platform
説明内容を見直し、文字列長制限内に収まるよう修正

2021-02-09 02:46 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      - 環境変数の確認<br>
説明内容を見直し、文字列長制限内に収まるよう修正

2021-02-10 06:29 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +React Nativeでアプリケーションを開発する為の環境構築手順です。環境構築を進める前に必要なツールが既にインストールされているか確認してください。併せてバージョンについても確認してください。必要なバージョンを満たしている場合は該当のツールの再インストールは不要です。満たしていない場合はアップデートしてください。
```suggestion
React Nativeでアプリケーションを開発するための環境構築手順です。環境構築を進める前に必要なツールが既にインストールされているか確認してください。併せてバージョンについても確認してください。必要なバージョンを満たしている場合は該当のツールの再インストールは不要です。満たしていない場合はアップデートしてください。
```

2021-02-10 06:37 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +必要なアプリケーションとバージョンの確認方法について、以下に纏めているので、確認してください。
```suggestion
## React Nativeでの開発に必要なツール
必要なツールとバージョンの確認方法について、以下に纏めているので、確認してください。
```
先頭の記述でアプリケーション -> ツールになおしてしまっているのでこちらも修正したほうが良いです。

2021-02-10 06:37 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### **必要なアプリケーションとバージョン**
```suggestion
### **必要なツールとバージョン**
```

2021-02-10 06:50 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      バージョン `v10.x.x` 以降であれば、OK。 例：コマンド実行結果、`v14.15.1`の場合、OK。
```suggestion
  1. Node.js<br>
      コマンドラインかターミナルで`node -v`を実行してください。  
      バージョン `v10.x.x` 以降であればOKです。  
      エラーが表示された場合、またはバージョンがv9以下の場合はインストールが必要です。
```

こんな感じはどうですか？

2021-02-10 06:53 UTC, tani-takanori commented on mobile-app-handson/content/docs/setup-env/_index.md
> +`react-native-cli` がローカル内にインストールされていると、アプリ実行時に失敗します。
```suggestion
`react-native-cli` がインストールされていると、アプリ実行時に失敗します。
```
インストール先に `ローカル内に` っていう言葉が初めて出てきますが、不要だと思います。

2021-02-10 07:53 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +React Nativeでアプリケーションを開発する為の環境構築手順です。環境構築を進める前に必要なツールが既にインストールされているか確認してください。併せてバージョンについても確認してください。必要なバージョンを満たしている場合は該当のツールの再インストールは不要です。満たしていない場合はアップデートしてください。
指摘箇所の文言について、修正しました。

2021-02-10 07:54 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +必要なアプリケーションとバージョンの確認方法について、以下に纏めているので、確認してください。
指摘箇所とその他の関連箇所について、修正しました。（アプリケーション→ツール）

2021-02-10 07:54 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +### **必要なアプリケーションとバージョン**
上記と併せて、対応しました。

2021-02-10 07:55 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +      バージョン `v10.x.x` 以降であれば、OK。 例：コマンド実行結果、`v14.15.1`の場合、OK。
頂いた案を元に見やすさの観点から修正しました。

2021-02-10 07:55 UTC, OshitaTatsuya commented on mobile-app-handson/content/docs/setup-env/_index.md
> +`react-native-cli` がローカル内にインストールされていると、アプリ実行時に失敗します。
不要な文言を削除しました。

2021-02-10 07:58 UTC, tani-takanori approved these changes

2021-02-10 09:06 UTC, in-a-paddy approved these changes
Markdownの書き方とか、他のドキュメントと並べて読んだ時の違和感がまだありますが、いったんApproveしておきます。

2021-02-10 09:06 UTC, shkozake approved these changes

2021-02-10 09:07 UTC, merged