修正 ディレクトリ構成の修正と不要なソース類の除去
ws-4020/mobile-app-handson pull request #4
Opened 2021-05-11 03:17 UTC by OshitaTatsuya

## ✅ What's done

- [x] ディレクトリ構成の見直し
- [x] バックエンド呼び出し部分の実装

## ⏸ What's not done

- 非同期処理部分の実装が未（実装方法が不明な為、要確認）

## Tests

- [x] ToDoアプリを起動して、ToDoリストの取得、登録、更新が可能であることを確認（実装部分の確認）

## Devices

- [x] iOS
  - [x] シミュレータ (iPhone 11/iOS 14.3)
- [x] Android
  - [x] エミュレータ (Pixel 2/Android 10)

## Other (messages to reviewers, concerns, etc.)
なし

2021-05-11 03:30 UTC, in-a-paddy commented
* リポジトリ分けるというのはどうなったんだっけ？
* Dockerとかも含めて全部MobileToDoAppの中に入れる？

2021-05-11 03:36 UTC, in-a-paddy requested changes

2021-05-11 03:36 UTC, in-a-paddy commented on MobileToDoApp/src/services/BackendSerivce.tsx
> +  const getTodos = async () => {
`BackendService`って`ToDoService`と`AuthService`に分けたんじゃないんっけ？

2021-05-11 03:36 UTC, in-a-paddy commented on MobileToDoApp/src/services/BackendSerivce.tsx
> +  const corsHandler: Middleware = {
モバイルアプリってCORS対応必要なの？Originが決められない気がするけど、、、
そういうセキュリティモデルになってない気がするな。
https://reactnative.dev/docs/network#using-other-networking-libraries
> The security model for XMLHttpRequest is different than on web as there is no concept of CORS in native apps.

2021-05-11 04:11 UTC, tani-takanori commented on MobileToDoApp/src/services/TodoService.tsx
> +let id: number;
idってBackendで採番するんじゃない？

2021-05-11 08:32 UTC, in-a-paddy requested changes

2021-05-11 08:32 UTC, in-a-paddy commented on MobileToDoApp/src/backend/generated-rest-client/apis/TodosApi.ts
> + * サービス開発ハンズオンで作成するToDoアプリのREST API。
サービス開発ハンズオンではないので直しておいて方が良さそう

2021-05-11 08:57 UTC, creature-water-valley commented on rest-api-secification/openapi.yaml
> +        '200':
201とかの方が良い気がします。

2021-05-11 08:57 UTC, creature-water-valley commented on rest-api-secification/openapi.yaml
> +        '200':
ここも201か204ですかね。
レスポンスがあるなら201かな？

2021-05-11 08:57 UTC, creature-water-valley commented on docker/docker-compose.dev.yml
> +    image: postgres:12
13を使用してもいい気がしますが、なんか12の方が使いたい理由とかがあるんですかね？

2021-05-11 09:19 UTC, tani-takanori commented on MobileToDoApp/src/backend/generated-rest-client/apis/TodosApi.ts
> + * サービス開発ハンズオンで作成するToDoアプリのREST API。
直した

2021-05-12 01:17 UTC, tani-takanori commented
今回の学習コンテンツで「認証API」は使用せず、認証機能（UI）はMockにするっていうことで始めていたのでOpenAPIから403削除しました。
これで正常系、異常系の学習回せそうかも確認したい

2021-05-12 01:37 UTC, tani-takanori commented on MobileToDoApp/src/services/TodoService.tsx
>  export type Todo = {
OpenAPIの`model`使うほうがいいのかな？

2021-05-12 08:28 UTC, tani-takanori commented on MobileToDoApp/src/backend/generated-rest-client/runtime.ts
> +export const BASE_PATH = "http://localhost:9080".replace(/\/+$/, "");
BASE_PATHでlocalhost指定だとExpoGoからつながらんので環境設定かなにかでHookできるようにする必要がある

2021-05-14 02:56 UTC, in-a-paddy requested changes

2021-05-14 03:22 UTC, in-a-paddy commented on MobileToDoApp/src/backend/generated-rest-client/runtime.ts
> +export const BASE_PATH = "http://192.168.1.9:9080".replace(/\/+$/, "");
作った後に修正していたものを誤ってコミットしていたそうです。

2021-05-14 04:50 UTC, tani-takanori commented on MobileToDoApp/src/services/TodoService.tsx
>  export type Todo = {
Modelを参照できるようにserviceからもexportした

2021-05-14 04:53 UTC, tani-takanori commented on MobileToDoApp/README.md
> +Expo Goアプリも含め、実デバイスで確認する場合は`src/backend/config.ts`のbasePathを自分のIPに修正してください。
出来てました！

2021-05-14 06:07 UTC, tani-takanori commented on MobileToDoApp/src/backend/generated-rest-client/runtime.ts
> +export const BASE_PATH = "http://localhost:9080".replace(/\/+$/, "");
Configで対応

2021-05-17 04:39 UTC, in-a-paddy commented on MobileToDoApp/src/screens/todo/TodoBoard.tsx
> +        .finally(() => setLoading(false));
isMountedを判定しといた方が安全そう

2021-05-17 04:39 UTC, in-a-paddy commented on MobileToDoApp/src/services/TodoService.tsx
> +        return Promise.reject(e.status);
bodyを握りつぶす必要はない気がする

2021-05-17 04:39 UTC, in-a-paddy commented on MobileToDoApp/src/services/TodoService.tsx
> +        return Promise.reject(e.status);
こっちもbodyは握りつぶさなくていいと思う

2021-05-17 04:39 UTC, in-a-paddy commented on MobileToDoApp/src/services/TodoService.tsx
> +            console.log(`Post Err(400) > ${text}`);
400固定ではない気がする

```suggestion
            console.log(`Post Err(${e.status}) > ${text}`);
```

2021-05-17 04:39 UTC, in-a-paddy commented on MobileToDoApp/src/services/TodoService.tsx
> +        if (e.status >= 400 && e.status < 500) {
この辺のハンドリングを個別にやってるのは良くない感じがする

2021-05-17 04:39 UTC, in-a-paddy commented on rest-api-specification/openapi.yaml
> +              examples:
404返さないからわかる気はするけど、0件の例をexamplesに足しておいてもいいかも？

2021-05-17 04:41 UTC, tani-takanori commented on MobileToDoApp/src/services/TodoService.tsx
> +        return Promise.reject(e.status);
これ別ブランチで直してる...

2021-05-17 06:18 UTC, tani-takanori commented on MobileToDoApp/src/services/TodoService.tsx
> +            console.log(`Post Err(400) > ${text}`);
こっちでログ出さないように直してます
https://github.com/ws-4020/mobile-app-handson/discussions/6

2021-05-17 06:34 UTC, tani-takanori commented on MobileToDoApp/src/services/TodoService.tsx
> +        if (e.status >= 400 && e.status < 500) {
https://github.com/ws-4020/mobile-app-handson/discussions/6 で切り出してます

2021-05-17 06:52 UTC, tani-takanori commented on MobileToDoApp/src/services/TodoService.tsx
> +        return Promise.reject(e.status);
じゃなくてbodyをふくめろってことなのか

2021-05-18 07:53 UTC, tani-takanori commented on rest-api-specification/openapi.yaml
> +              examples:
`-H "Prefer: example=empty"` で `[]` を返すexamplesを追加しました

2021-05-18 07:53 UTC, tani-takanori commented on MobileToDoApp/src/screens/todo/TodoBoard.tsx
> +        .finally(() => setLoading(false));
対応しました

2021-05-19 02:12 UTC, tani-takanori commented on MobileToDoApp/src/backend/generated-rest-client/models/InlineObject.ts
> +    if ((json === undefined) || (json === null)) {
わからんけどどこから使ってんだ？

2021-05-19 02:12 UTC, tani-takanori commented on MobileToDoApp/src/services/TodoService.tsx
> +        return Promise.reject(e.status);
エラーハンドリング側で対応してます

2021-05-19 02:13 UTC, tani-takanori commented on MobileToDoApp/src/services/TodoService.tsx
> +        return Promise.reject(e.status);
https://github.com/ws-4020/mobile-app-handson/pull/8/commits/d972a5be95a4191bcfc273db772fa827c9c9d50b

2021-05-19 02:13 UTC, tani-takanori commented on MobileToDoApp/src/services/TodoService.tsx
> +        return Promise.reject(e.status);
https://github.com/ws-4020/mobile-app-handson/pull/8/commits/d972a5be95a4191bcfc273db772fa827c9c9d50b

2021-05-19 02:13 UTC, tani-takanori commented on rest-api-specification/openapi.yaml
> +        登録しているToDoを全て取得する。
Discussionsに上げとく？

2021-05-19 02:29 UTC, tani-takanori commented on MobileToDoApp/src/backend/generated-rest-client/models/InlineObject.ts
> +    if ((json === undefined) || (json === null)) {
PUTのときにTodosApi.tsで使ってた。ServiceもチェックせずにそのままUI(screen)まで伝播してるけど、PUTは戻り値無視してるから動作に影響はなさそう。

2021-05-19 17:17 UTC, in-a-paddy commented on MobileToDoApp/src/backend/generated-rest-client/models/InlineObject.ts
> +    if ((json === undefined) || (json === null)) {
ふむ。どっちみち自動生成部分だもんね。
TypeScriptの型チェックが壊れてそうな気がするな、と思ったけどtscでエラーにならないってことはいいのかな。

2021-05-19 17:18 UTC, in-a-paddy commented on rest-api-specification/openapi.yaml
> +        登録しているToDoを全て取得する。
だね。「ページング＋スクロールでフェッチ」って結構ありがちなパターンかな、と思ったり。

2021-05-19 17:24 UTC, in-a-paddy approved these changes

2021-05-20 00:23 UTC, tani-takanori commented on rest-api-specification/openapi.yaml
> +        登録しているToDoを全て取得する。
https://github.com/ws-4020/mobile-app-crib-notes/discussions/234

2021-05-20 04:21 UTC, creature-water-valley approved these changes

2021-05-20 04:22 UTC, merged