エラーハンドリングのイメージ
ws-4020/mobile-app-handson pull request #8
Opened 2021-05-14 07:27 UTC by tani-takanori

エラーハンドリングの実装のイメージとUIの表示を作成してみる。

## Other

todo-apl-sampleがmasterに取り込まれたら、ブランチ作成し直します。

2021-05-17 01:48 UTC, tani-takanori commented
データが空の場合の処理も追加

2021-05-17 04:47 UTC, creature-water-valley commented on MobileToDoApp/src/screens/todo/TodoBoard.tsx
> +            setLoading(false);
`finally`でも良さそうな気がします。

2021-05-17 04:53 UTC, creature-water-valley commented
↓とかってあえて`useCallback`にしてないんですかね？（なんか、どこかでそのような会話を見たような、見てないような）
https://github.com/ws-4020/mobile-app-handson/pull/8/files#diff-2102862658ab6f288638e4d7fd21a5ded09c89e4df5e0880cf0ef066d889efe8R51

2021-05-17 06:45 UTC, tani-takanori commented on MobileToDoApp/src/screens/todo/TodoBoard.tsx
> +            setLoading(false);
`isMounted` 対応入れます。

2021-05-17 07:14 UTC, in-a-paddy requested changes

2021-05-17 07:14 UTC, in-a-paddy commented on MobileToDoApp/src/components/parts/todo/TodoList.tsx
> +              onDelete={(id) => removeTodo(id)}
これだとだめなんだっけ？？
```suggestion
              onDelete={removeTodo}
```

2021-05-17 08:23 UTC, tani-takanori commented on MobileToDoApp/src/screens/todo/TodoBoard.tsx
> +      .then(() => setIsEmptyList(removed.length === 0))
たしかに...
修正しました

2021-05-17 08:23 UTC, tani-takanori commented on MobileToDoApp/src/components/parts/todo/TodoList.tsx
> +              onDelete={(id) => removeTodo(id)}
いらなんので修正しました

2021-05-17 08:24 UTC, tani-takanori commented on MobileToDoApp/src/screens/todo/TodoBoard.tsx
> +          onPress={() => {
修正しました

2021-05-17 08:36 UTC, tani-takanori commented on MobileToDoApp/src/screens/todo/TodoBoard.tsx
> +            setIsEmptyList(response.length === 0);
https://github.com/ws-4020/mobile-app-handson/pull/8/commits/837f2497fbf74108954b82c736be9068a7d0c587

で対応してみた

2021-05-18 04:09 UTC, tani-takanori commented on MobileToDoApp/src/components/parts/todo/TodoList.tsx
> +          <>
（ここに削除ボタンつけようとしてFragmentにしてましたが、Item側に入れないとおかしかったので）不要です。

2021-05-18 04:11 UTC, tani-takanori commented on MobileToDoApp/src/screens/todo/TodoBoard.tsx
> +            setLoading(false);
https://github.com/ws-4020/mobile-app-handson/pull/8/commits/262fb3ae0b40e02599afadf4540979e706e32b45
対応入れました

2021-05-18 07:08 UTC, tani-takanori commented on MobileToDoApp/src/screens/todo/TodoBoard.tsx
> +  const toggleTodoCompletion = useCallback(
@creature-water-valley 
useCallbackの指摘ってこれですかね？（別件の指摘対応時に合わせて修正していたっぽいです）

2021-05-18 07:20 UTC, creature-water-valley commented on MobileToDoApp/src/screens/todo/TodoBoard.tsx
> +  const toggleTodoCompletion = useCallback(
ですです。
んでは、Resolveしちゃいます。

2021-05-18 07:25 UTC, tani-takanori commented on MobileToDoApp/src/components/parts/todo/TodoItem.tsx
> +      <AntDesign name="delete" size={24} onPress={() => onDelete(id)} />
修正しました

2021-05-19 06:42 UTC, creature-water-valley approved these changes

2021-05-19 17:34 UTC, in-a-paddy requested changes

2021-05-19 17:34 UTC, in-a-paddy commented on MobileToDoApp/src/components/parts/todo/TodoItem.tsx
> +import {AntDesign} from '@expo/vector-icons';
ESLintがwarning出してるね。

>   4:1  warning  `@expo/vector-icons` import should occur before import of `react`  import/order

2021-05-20 00:14 UTC, tani-takanori commented on MobileToDoApp/src/components/parts/todo/TodoItem.tsx
> +import {AntDesign} from '@expo/vector-icons';
修正しました

2021-05-20 01:42 UTC, merged